version: '3'

services:

  webapp:
    build: .
    container_name: hneu-personal-account-webapp
    links:
      - storage
    restart: always
    ports:
      - 80:8080

  storage:
    image: mysql
    container_name: hneu-personal-account-db
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    ports:
      - 3306:3306
    environment:
      MYSQL_USER: "stud_portal_admin"
      MYSQL_PASSWORD: "HNEUportal2017"
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_DATABASE: "stud_portal"
    restart: always
    volumes:
      - /tmp/mysql/data:/var/lib/mysql