server:
  port: 8080
db:
  driver: com.mysql.jdbc.Driver
  username: root
  password: root
  url: jdbc:mysql://localhost:3306/stud_portal

hibernate:
  dialect: org.hibernate.dialect.MySQL5InnoDBDialect
  show_sql: true
  format_sql: true
  hbm2ddl:
    auto: create

profile:
  photo:
    location: /img/
uploaded:
  files:
    location: /excel/
support:
  mail: lkhneu@hneu.net
decan:
  mail: dekanstei@gmail.com
schedule:
  url: http://services.ksue.edu.ua:8081/schedule/xml?auth=com.alcsan.atimetable_19092013_552ca3ffa5&group=%s&week=%s
emails:
  integration:
    service:
      url: http://212.111.199.46:65008
      #url: http://172.16.0.208:8080

security:
  oauth2:
    client:
      client-id: acme
      client-secret: acmesecret
      scope: read,write
      auto-approve-scopes: '.*'
google:
  client:
    clientId: 624736482499-j8aftskiu2rnpasgucc2fumgpulltka3.apps.googleusercontent.com
    clientSecret: MXEPao9tGhk8l5fkTZ5zsqVH
    accessTokenUri: https://www.googleapis.com/oauth2/v3/token
    userAuthorizationUri: https://accounts.google.com/o/oauth2/auth
    scope: email,https://www.googleapis.com/auth/gmail.send,https://mail.google.com/
    auto-approve-scopes: '.*'
    clientAuthenticationScheme: form
  resource:
    userInfoUri: https://www.googleapis.com/plus/v1/people/me
