spring:
  profiles:
    active: develop
  freemarker:
      template-loader-path: classpath:/emails/
db:
  driver: com.mysql.jdbc.Driver
  username: stud_portal_admin
  password: HNEUportal2017
  url: jdbc:mysql://localhost:3306/stud_portal?useUnicode=yes&characterEncoding=UTF-8&useSSL=false
hibernate:
  dialect: org.hibernate.dialect.MySQL5InnoDBDialect
  show_sql: false
  format_sql: true
  hbm2ddl:
    auto: update
integration:
  service:
    schedule:
      url: http://services.ksue.edu.ua:8081/schedule/xml?auth=com.alcsan.atimetable_19092013_552ca3ffa5&group=%s&week=%s
security:
  oauth2:
    client:
      client-id: acme
      client-secret: acmesecret
      scope: read,write
      auto-approve-scopes: '.*'
google:
  client:
    clientId: 624736482499-j8aftskiu2rnpasgucc2fumgpulltka3.apps.googleusercontent.com
    clientSecret: MXEPao9tGhk8l5fkTZ5zsqVH
    accessTokenUri: https://www.googleapis.com/oauth2/v3/token
    userAuthorizationUri: https://accounts.google.com/o/oauth2/auth
    scope: email,https://www.googleapis.com/auth/gmail.send,https://mail.google.com/
    auto-approve-scopes: '.*'
    clientAuthenticationScheme: form
  resource:
    userInfoUri: https://www.googleapis.com/plus/v1/people/me

---

spring:
  profiles: develop
integration:
  service:
    emails:
      url: http://212.111.199.46:65008
communication:
  mail:
    decan: oleksandr.rozdolskyi2012@gmail.com
    support:
      username: 'oleksandr.rozdolskyi2012@gmail.com'
      password: 'Rozdolski1994'

---

spring:
  profiles: production
integration:
  service:
    emails:
      url: http://172.16.0.208:8080
db:
  url: jdbc:mysql://storage:3306/stud_portal?useUnicode=yes&characterEncoding=UTF-8&useSSL=false
communication:
  mail:
    decan: dekanstei@gmail.com
    support:
      username: 'students.portal@hneu.net'
      password: 'Amn36z42S'

---

spring:
  profiles: init
hibernate:
  hbm2ddl:
    auto: create