INSERT INTO discipline(id,controlForm,course,credits,label,semester,type,education_program_id,speciality_id) VALUES (0,1,1,5,'Інтелектуальні методи та засоби обробки інформації',1,3,0,0);
INSERT INTO discipline(id,controlForm,course,credits,label,semester,type,education_program_id,speciality_id) VALUES (1,0,1,5,'Методології наукових досліджень',1,3,0,0);
INSERT INTO discipline(id,controlForm,course,credits,label,semester,type,education_program_id,speciality_id) VALUES (2,1,1,5,'Мережеві технології',1,3,0,0);
INSERT INTO discipline(id,controlForm,course,credits,label,semester,type,education_program_id,speciality_id) VALUES (3,1,1,5,'Розподілені сховища даних',1,3,0,0);
INSERT INTO discipline(id,controlForm,course,credits,label,semester,type,education_program_id,speciality_id) VALUES (4,0,1,4,'Сучасна теорія управління',2,3,0,0);
INSERT INTO discipline(id,controlForm,course,credits,label,semester,type,education_program_id,speciality_id) VALUES (5,1,1,5,'Технології обробки даних в інформаційно-комунікаційних системах',2,3,0,0);
INSERT INTO discipline(id,controlForm,course,credits,label,semester,type,education_program_id,speciality_id) VALUES (6,1,1,5,'Хмарні обчислення',2,3,0,0);
INSERT INTO discipline(id,controlForm,course,credits,label,semester,type,education_program_id,speciality_id) VALUES (7,1,1,5,'Методи оптимізації в задачах управління',2,3,0,0);
INSERT INTO discipline(id,controlForm,course,credits,label,semester,type,education_program_id,speciality_id) VALUES (8,2,1,1,'Науково-дослідна практика: Науковий семінар',2,3,0,0);
INSERT INTO discipline(id,controlForm,course,credits,label,semester,type,education_program_id,speciality_id) VALUES (9,2,2,3,'Комплексний тренінг',1,3,0,0);
INSERT INTO discipline(id,controlForm,course,credits,label,semester,type,education_program_id,speciality_id) VALUES (10,2,2,8,'Науково-дослідна практика: Консультаційний проект',1,3,0,0);
INSERT INTO discipline(id,controlForm,course,credits,label,semester,type,education_program_id,speciality_id) VALUES (11,2,2,4,'Переддипломна практика',1,3,0,0);
INSERT INTO discipline(id,controlForm,course,credits,label,semester,type,education_program_id,speciality_id) VALUES (12,3,2,15,'Дипломна робота',1,3,0,0);
